### ISSUE TITLE
Segmentation Fault in Aagos with Small Genomes

### ISSUE THREAD

**Issue by leg2015** [leg2015/Aagos#9]
- [x] Figure out what's causing segmentation fault 
   * Bad params: 
      * `-NUM_BITS` = 10
      *  `-NUM_GENES` = 3 
      * `-POP_SIZE` = 5 
      * `-GENE_SIZE` = 3 
   * throws a segmentation fault
- [ ] Find why `bin_array_offset` is producing a negative number with small genomes
   * subtracts `num_genes` from `min_size` to get `bin_array_offset`, which I'm not sure is right

**Comment by leg2015** [comment]
It appears that the issue is in finding the array offset to access the vector of binomial distributions - it's generating a negative number with small genomes. The problem line in question is https://github.com/leg2015/Aagos/blob/1da82396689449788319e3fd7f85ac226aeafab0/source/AagosWorld.h#L120. Not sure what this value is supposed to represent so will investigate that now. Also makes me wonder if it's working correctly for the default settings...

**Comment by mercere99** [comment]
Another way of solving this problem might be to do lazy building of distributions.  Then we also won't build extra ones for probabilities that are identical...

**Comment by mercere99** [comment]
I do wonder if it's worth doing some comparisons with the old system (on parameters that were quick) just to make sure we're getting qualitatively identical results...
